### ISSUE TITLE
LURs don't update the last accessed field in the TMSI table

### ISSUE THREAD

**Issue by shaddi** [endaga/openbts#11]
We don't update the last accessed field of the TMSI table when a phone sends a LUR, so we don't have a way to know when/what phones are camped. This used to work before the L3 rewrite.

**Comment by shaddi** [comment]
This is due to new default setting for T3212 timer to "disabled", so phones don't send regular LURs by default. Still keeping open for now until we make sure we've fixed #12 and #17.

**Comment by kheimerl** [comment]
You sure that's the cause? #17 seems like it would cause it too.

**Comment by shaddi** [comment]
Yes, this is verified as working.

**Comment by shaddi** [comment]
That said, we may still be missing some updates from a re-attach due to #17 but we're definitely seeing the expected behavior now with the config change.

In light of that actually I think we should just close this out.
