### ISSUE TITLE
Bad registrations

### ISSUE THREAD

**Issue by kheimerl** [endaga/openbts#31]
This is very high priority.

**Comment by kheimerl** [comment]
I copied the registration for 537 to 18, it should only need the cloud to point back in the right direction.

**Comment by kheimerl** [comment]
feel free to log into each IMSI as fake phone on 10 to test, or tell me when things should work and I will

**Comment by yosemitebandit** [comment]
I can fix it in a bit when I'm back online but if you guys have staff.endaga access that should work too

**Comment by yosemitebandit** [comment]
ok, got a seat on the train and am looking into it on staff.endaga..

**Comment by kheimerl** [comment]
yeah I dunno how to edit this, but 537 needs to be changed from 10.64.1.42 to 10.64.0.218

**Comment by kheimerl** [comment]
and then *I think* that should be it for that one

**Comment by kheimerl** [comment]
wait uuid need to be changed too

**Comment by yosemitebandit** [comment]
changed 537 to 10.64.0.218

**Comment by yosemitebandit** [comment]
UUID of the box needs to be changed?

**Comment by kheimerl** [comment]
resolved
