### ISSUE TITLE
Livelocks

### ISSUE THREAD

**Issue by kheimerl** [endaga/openbts#32]
Boxes were locked up after 47 hours of operation. Not sure what happened, reset to resolve issue for customer quickly.

**Comment by kheimerl** [comment]
Might not be deadlock, operation continues but log complains about CLI issue. Impacts IMSI reporting though to dashboard.

**Comment by yosemitebandit** [comment]
can you include the log lines with the CLI issue?  There is a GPRS scraper hitting the CLI frequently, maybe that's the culprit?

**Comment by kheimerl** [comment]
Definitely could be. Everything's running now, but I'll add them when I see it again.

**Comment by kheimerl** [comment]
Jul 10 18:10:09 openbts: message repeated 929 times: [ ERR 3505:3505 2015-07-10T18:10:09.2 CLIServer.cpp:170:cliServer: can't accept network stream connection]

**Comment by kheimerl** [comment]
Error number logging added to that output, we'll see once it manifests again.

**Comment by kheimerl** [comment]
Error code is 24: 

#define EMFILE          24      /* Too many open files */

What?

**Comment by kheimerl** [comment]
@kkroo broke it!

OpenBTS 14975 root 1009ur  REG       0,16     5120       9190 /run/TMSITable.db
OpenBTS 14975 root 1010u   REG       0,16   855200       9196 /run/TMSITable.db-wal
OpenBTS 14975 root 1011ur  REG       0,16     5120       9190 /run/TMSITable.db
OpenBTS 14975 root 1012u   REG       0,16   855200       9196 /run/TMSITable.db-wal
OpenBTS 14975 root 1013ur  REG       0,16     5120       9190 /run/TMSITable.db
OpenBTS 14975 root 1014u   REG       0,16   855200       9196 /run/TMSITable.db-wal
OpenBTS 14975 root 1015ur  REG       0,16     5120       9190 /run/TMSITable.db
OpenBTS 14975 root 1016u   REG       0,16   855200       9196 /run/TMSITable.db-wal
OpenBTS 14975 root 1017ur  REG       0,16     5120       9190 /run/TMSITable.db
OpenBTS 14975 root 1018u   REG       0,16   855200       9196 /run/TMSITable.db-wal
OpenBTS 14975 root 1019ur  REG       0,16     5120       9190 /run/TMSITable.db
OpenBTS 14975 root 1020u   REG       0,16   855200       9196 /run/TMSITable.db-wal
OpenBTS 14975 root 1021ur  REG       0,16     5120       9190 /run/TMSITable.db
OpenBTS 14975 root 1022u   REG       0,16   855200       9196 /run/TMSITable.db-wal
OpenBTS 14975 root 1023ur  REG       0,16     5120       9190 /run/TMSITable.db
endaga@endaga:~$

**Comment by yosemitebandit** [comment]
hm, this is reminiscent of the JSONDB issue I had a while back where `disconnect` wasn't getting called and so the sqlite db connection wasn't getting closed.  I added a lot of `disconnect`s to `NodeManager/JSONDB/JSONDB.cpp`

But now I see that the openbts repo's master has the NodeManager submodule at commit 896b3ef which does not have my `disconnect`s..  Can we update the submodule to point to master?

**Comment by kheimerl** [comment]
I built this against master in CommonLibs, so I don't think this is the issue.

**Comment by yosemitebandit** [comment]
CommonLibs != the NM submodule though..

**Comment by kheimerl** [comment]
Sorry, nodemanager is also up to date

**Comment by kheimerl** [comment]
Unless I'm confused: 

diff --git a/NodeManager b/NodeManager
index 896b3ef..4b60fc9 160000
--- a/NodeManager
+++ b/NodeManager
@@ -1 +1 @@
-Subproject commit 896b3ef67ab00db301bf9d449ecf8de6a377b6f9
+Subproject commit 4b60fc9772ab445c46a3d741d3d34d4bf1fac936
kheimerl@palpatine:~/src/endaga/openbts$ cd NodeManager/
kheimerl@palpatine:~/src/endaga/openbts/NodeManager$ git pull
Already up-to-date.

**Comment by kheimerl** [comment]
Actually this could be pulling from Range instead for some reason? Our commit hashes don't line up.

**Comment by yosemitebandit** [comment]
hm, I think we want to build NM at commit `fae56`

**Comment by yosemitebandit** [comment]
yah, I think `4b60` is Range?

**Comment by kheimerl** [comment]
Got it, will test today

**Comment by kkroo** [comment]
nice catch guys

**Comment by kheimerl** [comment]
Seems to be working btw, file ownership is reasonable

**Comment by kkroo** [comment]
Great! I guess we can make a minor release once we merge in #37

**Comment by kheimerl** [comment]
Resolved, needs to be pushed to repo.
