### ISSUE TITLE
Camped status not correct on dashboard

### ISSUE THREAD

**Issue by Mrigank0707** [endaga/openbts#36]
Noob issue reporting ... pardon any mistakes !!

I left the phones connected and when I came back the status for both the phones in the dashboard was "Not Camped".

Kurtis knows more about the issue.

**Comment by kheimerl** [comment]
Very likely related to #32, as the CLI was hung and thus OpenBTS may not have been forwarding the LURs any more.

**Comment by kheimerl** [comment]
Fix to #32 is pushed, this is likely resolved as well. Closing for now unless we see it again.
